// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakerStore.Services.CouponAPI.Data;

#nullable disable

namespace SneakerStore.Services.ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240930130040_AddProdutTodb")]
    partial class AddProdutTodb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SneakerStore.Services.ProductApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Sneakers",
                            Description = "Classic red and black high-tops",
                            ImageUrl = "https://example.com/images/air_jordan_1.jpg",
                            Name = "Air Jordan 1 Retro High",
                            Price = 199.99000000000001
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Sneakers",
                            Description = "Ultra-comfortable with a sleek design",
                            ImageUrl = "https://example.com/images/yeezy_boost_350.jpg",
                            Name = "Adidas Yeezy Boost 350 V2",
                            Price = 299.99000000000001
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Sneakers",
                            Description = "Timeless running shoes with a bold look",
                            ImageUrl = "https://example.com/images/air_max_90.jpg",
                            Name = "Nike Air Max 90",
                            Price = 149.99000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Sneakers",
                            Description = "Iconic suede sneakers",
                            ImageUrl = "https://example.com/images/puma_suede.jpg",
                            Name = "Puma Suede Classic",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Sneakers",
                            Description = "Retro-inspired sneakers",
                            ImageUrl = "https://example.com/images/reebok_club_c.jpg",
                            Name = "Reebok Club C 85",
                            Price = 74.989999999999995
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Sneakers",
                            Description = "Comfort meets style in these everyday trainers",
                            ImageUrl = "https://example.com/images/new_balance_990.jpg",
                            Name = "New Balance 990v5",
                            Price = 179.99000000000001
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "Sneakers",
                            Description = "The timeless canvas shoes",
                            ImageUrl = "https://example.com/images/converse_chuck_taylor.jpg",
                            Name = "Converse Chuck Taylor All Star",
                            Price = 55.0
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "Sneakers",
                            Description = "Skater's favorite with a stripe",
                            ImageUrl = "https://example.com/images/vans_old_skool.jpg",
                            Name = "Vans Old Skool",
                            Price = 60.0
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "Sneakers",
                            Description = "Performance basketball shoes",
                            ImageUrl = "https://example.com/images/under_armour_curry.jpg",
                            Name = "Under Armour Curry 7",
                            Price = 159.99000000000001
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryName = "Sneakers",
                            Description = "Ultimate support for long-distance running",
                            ImageUrl = "https://example.com/images/asics_gel_kayano.jpg",
                            Name = "ASICS Gel-Kayano 26",
                            Price = 179.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
